namespace:
  name: prod 
 
service:
  port: 7111
#  type: ClusterIP

image:
#  repository: mctsm/techtrends
#  tag: 1.0.0
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    cpu: "500m"
    memory: "250Mi"
    

#configmap:
 # data: "version: 1.17.0"
