namespace:
  name: sandbox
 
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: mctsm/techtrends
  tag: v1.0.0
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
    requests:
            memory: "64Mi"
            cpu: "250m"
    limits:
            memory: "128Mi"
            cpu: "500m"

spec:
     containers:
	     ports:
               - containerPort: 3111

livenessProbe:
   httpGet:
          path: /healthz

readinessProbe:
   httpGet:
          path: /healthz
             
