apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      - values-prod.yaml
    path: manifests
    repoURL: https://github.com/mctsm/techtest
    targetRevision: HEAD
  syncPolicy: {}

